onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /mp3_tb/clk
add wave -noupdate /mp3_tb/pmem_resp
add wave -noupdate /mp3_tb/pmem_read
add wave -noupdate /mp3_tb/pmem_write
add wave -noupdate /mp3_tb/pmem_address
add wave -noupdate /mp3_tb/pmem_wdata
add wave -noupdate /mp3_tb/pmem_rdata
add wave -noupdate /mp3_tb/write_data
add wave -noupdate /mp3_tb/write_address
add wave -noupdate /mp3_tb/write
add wave -noupdate /mp3_tb/halt
add wave -noupdate /mp3_tb/dut/instruction_cache/datapath/data_array0/data
add wave -noupdate /mp3_tb/dut/instruction_cache/datapath/data_array1/data
add wave -noupdate /mp3_tb/dut/data_cache/datapath/data_array0/data
add wave -noupdate /mp3_tb/dut/data_cache/datapath/data_array1/data
add wave -noupdate /mp3_tb/dut/cpu/regfile/data
add wave -noupdate /mp3_tb/dut/arbiter/clk
add wave -noupdate /mp3_tb/dut/arbiter/pmem_read_i
add wave -noupdate /mp3_tb/dut/arbiter/pmem_write_i
add wave -noupdate /mp3_tb/dut/arbiter/pmem_read_d
add wave -noupdate /mp3_tb/dut/arbiter/pmem_write_d
add wave -noupdate /mp3_tb/dut/arbiter/pmem_resp
add wave -noupdate /mp3_tb/dut/arbiter/pmem_address_i
add wave -noupdate /mp3_tb/dut/arbiter/pmem_address_d
add wave -noupdate /mp3_tb/dut/arbiter/pmem_wdata_i
add wave -noupdate /mp3_tb/dut/arbiter/pmem_wdata_d
add wave -noupdate /mp3_tb/dut/arbiter/pmem_rdata
add wave -noupdate /mp3_tb/dut/arbiter/pmem_resp_i
add wave -noupdate /mp3_tb/dut/arbiter/pmem_resp_d
add wave -noupdate /mp3_tb/dut/arbiter/pmem_read
add wave -noupdate /mp3_tb/dut/arbiter/pmem_write
add wave -noupdate /mp3_tb/dut/arbiter/pmem_address
add wave -noupdate /mp3_tb/dut/arbiter/pmem_rdata_i
add wave -noupdate /mp3_tb/dut/arbiter/pmem_rdata_d
add wave -noupdate /mp3_tb/dut/arbiter/pmem_wdata
add wave -noupdate /mp3_tb/dut/arbiter/address
add wave -noupdate /mp3_tb/dut/arbiter/mem_addrmux_sel
add wave -noupdate /mp3_tb/dut/cpu/read_a
add wave -noupdate /mp3_tb/dut/cpu/address_a
add wave -noupdate /mp3_tb/dut/cpu/resp_a
add wave -noupdate /mp3_tb/dut/cpu/rdata_a
add wave -noupdate /mp3_tb/dut/cpu/read_b
add wave -noupdate /mp3_tb/dut/cpu/write_b
add wave -noupdate /mp3_tb/dut/cpu/address_b
add wave -noupdate /mp3_tb/dut/cpu/wdata_b
add wave -noupdate /mp3_tb/dut/cpu/resp_b
add wave -noupdate /mp3_tb/dut/cpu/rdata_b
add wave -noupdate /mp3_tb/dut/cpu/pcmux/sel
add wave -noupdate /mp3_tb/dut/cpu/pcmux/a
add wave -noupdate /mp3_tb/dut/cpu/pcmux/b
add wave -noupdate /mp3_tb/dut/cpu/pcmux/f
add wave -noupdate /mp3_tb/dut/cpu/pc/clk
add wave -noupdate /mp3_tb/dut/cpu/pc/load
add wave -noupdate /mp3_tb/dut/cpu/pc/in
add wave -noupdate /mp3_tb/dut/cpu/pc/out
add wave -noupdate /mp3_tb/dut/cpu/pc/data
add wave -noupdate /mp3_tb/dut/cpu/if_id/clk
add wave -noupdate /mp3_tb/dut/cpu/if_id/load
add wave -noupdate /mp3_tb/dut/cpu/if_id/clear
add wave -noupdate /mp3_tb/dut/cpu/if_id/read_data_in
add wave -noupdate /mp3_tb/dut/cpu/if_id/pc_in
add wave -noupdate /mp3_tb/dut/cpu/if_id/pc_out
add wave -noupdate /mp3_tb/dut/cpu/if_id/rs1
add wave -noupdate /mp3_tb/dut/cpu/if_id/rs2
add wave -noupdate /mp3_tb/dut/cpu/if_id/rd
add wave -noupdate /mp3_tb/dut/cpu/if_id/u_imm
add wave -noupdate /mp3_tb/dut/cpu/if_id/b_imm
add wave -noupdate /mp3_tb/dut/cpu/if_id/s_imm
add wave -noupdate /mp3_tb/dut/cpu/if_id/j_imm
add wave -noupdate /mp3_tb/dut/cpu/if_id/i_imm
add wave -noupdate /mp3_tb/dut/cpu/if_id/opcode
add wave -noupdate /mp3_tb/dut/cpu/if_id/funct3
add wave -noupdate /mp3_tb/dut/cpu/if_id/funct7
add wave -noupdate /mp3_tb/dut/cpu/if_id/data
add wave -noupdate /mp3_tb/dut/cpu/if_id/pc
add wave -noupdate /mp3_tb/dut/cpu/id_ex/clk
add wave -noupdate /mp3_tb/dut/cpu/id_ex/load
add wave -noupdate /mp3_tb/dut/cpu/id_ex/clear
add wave -noupdate /mp3_tb/dut/cpu/id_ex/control_word_in
add wave -noupdate /mp3_tb/dut/cpu/id_ex/pc_in
add wave -noupdate /mp3_tb/dut/cpu/id_ex/rd_in
add wave -noupdate /mp3_tb/dut/cpu/id_ex/u_imm_in
add wave -noupdate /mp3_tb/dut/cpu/id_ex/b_imm_in
add wave -noupdate /mp3_tb/dut/cpu/id_ex/s_imm_in
add wave -noupdate /mp3_tb/dut/cpu/id_ex/j_imm_in
add wave -noupdate /mp3_tb/dut/cpu/id_ex/i_imm_in
add wave -noupdate /mp3_tb/dut/cpu/id_ex/rs1_data_in
add wave -noupdate /mp3_tb/dut/cpu/id_ex/rs2_data_in
add wave -noupdate /mp3_tb/dut/cpu/id_ex/pc_out
add wave -noupdate /mp3_tb/dut/cpu/id_ex/control_word_out
add wave -noupdate /mp3_tb/dut/cpu/id_ex/rs1_data_out
add wave -noupdate /mp3_tb/dut/cpu/id_ex/rs2_data_out
add wave -noupdate /mp3_tb/dut/cpu/id_ex/rd_out
add wave -noupdate /mp3_tb/dut/cpu/id_ex/u_imm_out
add wave -noupdate /mp3_tb/dut/cpu/id_ex/b_imm_out
add wave -noupdate /mp3_tb/dut/cpu/id_ex/s_imm_out
add wave -noupdate /mp3_tb/dut/cpu/id_ex/j_imm_out
add wave -noupdate /mp3_tb/dut/cpu/id_ex/i_imm_out
add wave -noupdate /mp3_tb/dut/cpu/id_ex/pc
add wave -noupdate /mp3_tb/dut/cpu/id_ex/i_imm
add wave -noupdate /mp3_tb/dut/cpu/id_ex/s_imm
add wave -noupdate /mp3_tb/dut/cpu/id_ex/b_imm
add wave -noupdate /mp3_tb/dut/cpu/id_ex/u_imm
add wave -noupdate /mp3_tb/dut/cpu/id_ex/j_imm
add wave -noupdate /mp3_tb/dut/cpu/id_ex/rs1_data
add wave -noupdate /mp3_tb/dut/cpu/id_ex/rs2_data
add wave -noupdate /mp3_tb/dut/cpu/id_ex/rd
add wave -noupdate /mp3_tb/dut/cpu/ex_mem/clk
add wave -noupdate /mp3_tb/dut/cpu/ex_mem/load
add wave -noupdate /mp3_tb/dut/cpu/ex_mem/clear
add wave -noupdate /mp3_tb/dut/cpu/ex_mem/control_word_in
add wave -noupdate /mp3_tb/dut/cpu/ex_mem/pc_in
add wave -noupdate /mp3_tb/dut/cpu/ex_mem/rd_in
add wave -noupdate /mp3_tb/dut/cpu/ex_mem/rs2_data_in
add wave -noupdate /mp3_tb/dut/cpu/ex_mem/cmp_data_in
add wave -noupdate /mp3_tb/dut/cpu/ex_mem/alu_data_in
add wave -noupdate /mp3_tb/dut/cpu/ex_mem/u_ex
add wave -noupdate /mp3_tb/dut/cpu/ex_mem/u_mem
add wave -noupdate /mp3_tb/dut/cpu/ex_mem/pc_out
add wave -noupdate /mp3_tb/dut/cpu/ex_mem/control_word_out
add wave -noupdate /mp3_tb/dut/cpu/ex_mem/rs2_data_out
add wave -noupdate /mp3_tb/dut/cpu/ex_mem/cmp_data_out
add wave -noupdate /mp3_tb/dut/cpu/ex_mem/alu_data_out
add wave -noupdate /mp3_tb/dut/cpu/ex_mem/rd_out
add wave -noupdate /mp3_tb/dut/cpu/ex_mem/pc
add wave -noupdate /mp3_tb/dut/cpu/ex_mem/control_word
add wave -noupdate /mp3_tb/dut/cpu/ex_mem/rs2_data
add wave -noupdate /mp3_tb/dut/cpu/ex_mem/alu_data
add wave -noupdate /mp3_tb/dut/cpu/ex_mem/cmp_data
add wave -noupdate /mp3_tb/dut/cpu/ex_mem/rd
add wave -noupdate /mp3_tb/dut/cpu/mem_wb/clk
add wave -noupdate /mp3_tb/dut/cpu/mem_wb/load
add wave -noupdate /mp3_tb/dut/cpu/mem_wb/clear
add wave -noupdate /mp3_tb/dut/cpu/mem_wb/control_word_in
add wave -noupdate /mp3_tb/dut/cpu/mem_wb/resp_b_in
add wave -noupdate /mp3_tb/dut/cpu/mem_wb/rd_in
add wave -noupdate /mp3_tb/dut/cpu/mem_wb/mem_rdata_in
add wave -noupdate /mp3_tb/dut/cpu/mem_wb/alu_data_in
add wave -noupdate /mp3_tb/dut/cpu/mem_wb/u_mem
add wave -noupdate /mp3_tb/dut/cpu/mem_wb/br_en
add wave -noupdate /mp3_tb/dut/cpu/mem_wb/pc_mem
add wave -noupdate /mp3_tb/dut/cpu/mem_wb/pc_wb
add wave -noupdate /mp3_tb/dut/cpu/mem_wb/br_en_zext
add wave -noupdate /mp3_tb/dut/cpu/mem_wb/u_wb
add wave -noupdate /mp3_tb/dut/cpu/mem_wb/control_word_out
add wave -noupdate /mp3_tb/dut/cpu/mem_wb/resp_b_out
add wave -noupdate /mp3_tb/dut/cpu/mem_wb/rd_out
add wave -noupdate /mp3_tb/dut/cpu/mem_wb/mem_rdata_out
add wave -noupdate /mp3_tb/dut/cpu/mem_wb/alu_data_out
add wave -noupdate /mp3_tb/dut/cpu/mem_wb/control_word
add wave -noupdate /mp3_tb/dut/cpu/mem_wb/resp_b
add wave -noupdate /mp3_tb/dut/cpu/mem_wb/rd
add wave -noupdate /mp3_tb/dut/cpu/mem_wb/mem_rdata
add wave -noupdate /mp3_tb/dut/cpu/mem_wb/alu_data
add wave -noupdate /mp3_tb/dut/cpu/mem_wb/u_imm
add wave -noupdate /mp3_tb/dut/cpu/mem_wb/pc
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {1055114 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 293
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {2100 ns}
