onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /mp1_tb/clk
add wave -noupdate /mp1_tb/mem_resp
add wave -noupdate /mp1_tb/mem_read
add wave -noupdate /mp1_tb/mem_write
add wave -noupdate /mp1_tb/mem_byte_enable
add wave -noupdate /mp1_tb/mem_address
add wave -noupdate /mp1_tb/mem_rdata
add wave -noupdate /mp1_tb/mem_wdata
add wave -noupdate /mp1_tb/write_data
add wave -noupdate /mp1_tb/write_address
add wave -noupdate /mp1_tb/write
add wave -noupdate /mp1_tb/halt
add wave -noupdate /mp1_tb/clk
add wave -noupdate /mp1_tb/mem_resp
add wave -noupdate /mp1_tb/mem_read
add wave -noupdate /mp1_tb/mem_write
add wave -noupdate /mp1_tb/mem_byte_enable
add wave -noupdate /mp1_tb/mem_address
add wave -noupdate /mp1_tb/mem_rdata
add wave -noupdate /mp1_tb/mem_wdata
add wave -noupdate /mp1_tb/write_data
add wave -noupdate /mp1_tb/write_address
add wave -noupdate /mp1_tb/write
add wave -noupdate /mp1_tb/halt
add wave -noupdate /mp1_tb/dut/datapath/alumux1/sel
add wave -noupdate /mp1_tb/dut/datapath/alumux1/a
add wave -noupdate /mp1_tb/dut/datapath/alumux1/b
add wave -noupdate /mp1_tb/dut/datapath/alumux1/f
add wave -noupdate /mp1_tb/dut/datapath/alumux2/sel
add wave -noupdate /mp1_tb/dut/datapath/alumux2/a
add wave -noupdate /mp1_tb/dut/datapath/alumux2/b
add wave -noupdate /mp1_tb/dut/datapath/alumux2/c
add wave -noupdate /mp1_tb/dut/datapath/alumux2/d
add wave -noupdate /mp1_tb/dut/datapath/alumux2/e
add wave -noupdate /mp1_tb/dut/datapath/alumux2/f
add wave -noupdate /mp1_tb/dut/datapath/alumux2/g
add wave -noupdate /mp1_tb/dut/datapath/alumux2/h
add wave -noupdate /mp1_tb/dut/datapath/alumux2/out
add wave -noupdate /mp1_tb/dut/datapath/alu/aluop
add wave -noupdate /mp1_tb/dut/datapath/alu/a
add wave -noupdate /mp1_tb/dut/datapath/alu/b
add wave -noupdate /mp1_tb/dut/datapath/alu/f
add wave -noupdate /mp1_tb/clk
add wave -noupdate /mp1_tb/mem_resp
add wave -noupdate /mp1_tb/mem_read
add wave -noupdate /mp1_tb/mem_write
add wave -noupdate /mp1_tb/mem_byte_enable
add wave -noupdate /mp1_tb/mem_address
add wave -noupdate /mp1_tb/mem_rdata
add wave -noupdate /mp1_tb/mem_wdata
add wave -noupdate /mp1_tb/write_data
add wave -noupdate /mp1_tb/write_address
add wave -noupdate /mp1_tb/write
add wave -noupdate /mp1_tb/halt
add wave -noupdate /mp1_tb/registers
add wave -noupdate /mp1_tb/dut/datapath/regfile/clk
add wave -noupdate /mp1_tb/dut/datapath/regfile/load
add wave -noupdate /mp1_tb/dut/datapath/regfile/in
add wave -noupdate /mp1_tb/dut/datapath/regfile/src_a
add wave -noupdate /mp1_tb/dut/datapath/regfile/src_b
add wave -noupdate /mp1_tb/dut/datapath/regfile/dest
add wave -noupdate /mp1_tb/dut/datapath/regfile/reg_a
add wave -noupdate /mp1_tb/dut/datapath/regfile/reg_b
add wave -noupdate /mp1_tb/dut/control/state
add wave -noupdate /mp1_tb/dut/control/next_state
add wave -noupdate /mp1_tb/dut/control/funct7
add wave -noupdate /mp1_tb/dut/datapath/IR/funct7
add wave -noupdate /mp1_tb/dut/datapath/IR/in
add wave -noupdate /mp1_tb/dut/datapath/IR/data
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {2864047 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 215
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {2863552 ps} {2867288 ps}
